In [1]:
from pyagadir.models import AGADIR
from pyagadir.models import get_dG_dipole, get_dG_Int, get_dG_i1, get_dG_i3, get_dG_i4, get_dG_Ncap, get_dG_Ccap, get_dG_Hbond
import numpy as np

In [2]:
get_dG_Hbond('DSTAAREK')

-1.55

In [3]:
get_dG_dipole('DSTAAREK')

(array([-0.34,  0.  ,  0.  ,  0.  ,  0.  ,  0.21, -0.13,  0.2 ]),
 array([ 0.13,  0.  ,  0.  ,  0.  ,  0.  , -0.26,  0.46, -0.51]))

In [4]:
get_dG_Int('DSTAAREK')

array([0.  , 1.13, 1.18, 0.61, 0.61, 0.67, 0.95, 0.  ])

In [5]:
get_dG_i1('DSTAAREK')

array([ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.05, -0.05,  0.  ])

In [6]:
get_dG_i3('DSTAAREK')

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
get_dG_i4('DSTAAREK')

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
get_dG_Ncap('DSTAAREK')

0.0

In [9]:
get_dG_Ccap('DSTAAREK')

0.0

In [10]:
model = AGADIR(method='1s')
result = model.predict('ILKSLEEFLKVTLRSTRQT', )
print(result.get_percent_helix())
print(result.get_helical_propensity())
# print(result.get_helix_contributions())
# print(result.get_separate_helix_contributions())
# print(result.get_initialized_params())

case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
case 1
11.95
[ 0.          1.08484818  2.16965392  4.01743843 24.54926166 27.04674617
 28.970249   29.48441833 29.00689759 24.86694912 19.50355355 14.64421709
 11.04377445  5.3738644   2.64649844  1.50366438  0.92033324  0.30137058
  0.        ]


[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [2]:
print('res aa helix')
for i, aa in enumerate(result.get_sequence()):
    print(f'{i+1} {aa} {result.get_helical_propensity()[i]*100:.2f}')

res aa helix


NameError: name 'result' is not defined

In [2]:
model = AGADIR(method='1s')
result = model.predict('AAAAAA', )
print(result.get_percent_helix())
print(result.get_helical_propensity())
# print(result.get_helix_contributions())
# print(result.get_initialized_params())

0.38
[0.         0.57125393 0.57125393 0.57125393 0.57125393 0.        ]


In [5]:

print('res aa helix')
for i, aa in enumerate(result.get_sequence()):
    print(f'{i+1} {aa} {result.get_helical_propensity()[i]*100:.2f}')



res aa helix
1 I 0.00
2 L 1.41
3 K 2.57
4 S 4.67
5 L 30.91
6 E 31.31
7 E 31.68
8 F 31.63
9 L 30.95
10 K 27.09
11 V 22.97
12 T 20.98
13 L 14.91
14 R 5.67
15 S 3.40
16 T 2.11
17 R 1.05
18 Q 0.00
19 T 0.00


In [3]:
i = 0
j = 6
[1,2,3,4,5,6][i:j]

[1, 2, 3, 4, 5, 6]

In [3]:
[1,2,3,4,5,6][-0]

1

In [4]:
[1,2,3,4,5,6][6-1]

6

In [12]:
result.K_tot

0.005745359877457099

In [13]:
result.K_tot_array

array([0.        , 0.00574536, 0.00574536, 0.00574536, 0.00574536,
       0.        ])

In [6]:
result.dG_dict_mat[5]

[{'dG_Helix': 3.81,
  'dG_Int': 3.49,
  'dG_Hbond': -0.0,
  'dG_SD': -0.2,
  'dG_nonH': 0.48000000000000004,
  'dG_dipole': 0.03999999999999998,
  'dG_N_dipole': 0.38,
  'dG_C_dipole': -0.34,
  'dG_i1_tot': 0.0,
  'dG_i3_tot': -0.2,
  'dG_i4_tot': 0,
  'dG_Ncap': 0.4,
  'dG_Ccap': 0.08},
 {'dG_Helix': 4.34,
  'dG_Int': 3.6399999999999997,
  'dG_Hbond': -0.0,
  'dG_SD': -0.1,
  'dG_nonH': 0.48000000000000004,
  'dG_dipole': 0.32,
  'dG_N_dipole': 0.24,
  'dG_C_dipole': 0.08000000000000002,
  'dG_i1_tot': 0.0,
  'dG_i3_tot': -0.1,
  'dG_i4_tot': 0,
  'dG_Ncap': 0.4,
  'dG_Ccap': 0.08},
 {'dG_Helix': 4.41,
  'dG_Int': 3.83,
  'dG_Hbond': -0.0,
  'dG_SD': 0.05,
  'dG_nonH': 0.08,
  'dG_dipole': 0.45000000000000007,
  'dG_N_dipole': -0.41000000000000003,
  'dG_C_dipole': 0.8600000000000001,
  'dG_i1_tot': 0.05,
  'dG_i3_tot': 0.0,
  'dG_i4_tot': 0,
  'dG_Ncap': 0.0,
  'dG_Ccap': 0.08},
 {'dG_Helix': 2.8400000000000003,
  'dG_Int': 3.7800000000000002,
  'dG_Hbond': -0.0,
  'dG_SD': -0.25,
  

In [14]:
model = AGADIR(method='1s')
result = model.predict('TYQEKAAREVAMKKG')
result.get_percent_helix()

case 1
case 1


0.308

In [17]:
result.dG_dict_mat[8]

[{'dG_Helix': 4.785,
  'dG_Int': 6.470000000000001,
  'dG_Hbond': -2.325,
  'dG_SD': -0.6000000000000001,
  'dG_nonH': 0.48000000000000004,
  'dG_dipole': 0.7600000000000001,
  'dG_N_dipole': 0.05000000000000002,
  'dG_C_dipole': 0.7100000000000001,
  'dG_i1_tot': 0.05,
  'dG_i3_tot': -0.6000000000000001,
  'dG_i4_tot': -0.04999999999999999,
  'dG_Ncap': 0.4,
  'dG_Ccap': 0.08},
 {'dG_Helix': 4.3149999999999995,
  'dG_Int': 6.47,
  'dG_Hbond': -2.325,
  'dG_SD': -0.75,
  'dG_nonH': 0.4,
  'dG_dipole': 0.52,
  'dG_N_dipole': 0.06,
  'dG_C_dipole': 0.4600000000000001,
  'dG_i1_tot': 0.05,
  'dG_i3_tot': -0.4,
  'dG_i4_tot': -0.4,
  'dG_Ncap': 0.4,
  'dG_Ccap': 0.0},
 {'dG_Helix': 3.124999999999999,
  'dG_Int': 6.47,
  'dG_Hbond': -2.325,
  'dG_SD': -0.78,
  'dG_nonH': 0.08,
  'dG_dipole': -0.32000000000000006,
  'dG_N_dipole': -0.17000000000000004,
  'dG_C_dipole': -0.15,
  'dG_i1_tot': 0.05,
  'dG_i3_tot': -0.4,
  'dG_i4_tot': -0.43000000000000005,
  'dG_Ncap': 0.0,
  'dG_Ccap': 0.08},


In [6]:
model = AGADIR(method='1s')
result = model.predict('ILKSLEEFLKVTLRSTRQT')

In [7]:
result.get_helical_propensity()

array([0.        , 0.0092098 , 0.01694966, 0.03162682, 0.29314396,
       0.29863254, 0.30385508, 0.3068975 , 0.30417774, 0.29359725,
       0.24265173, 0.19342206, 0.17600071, 0.11319138, 0.03893537,
       0.02254033, 0.01372473, 0.00672205, 0.        ])

In [8]:
result.get_percent_helix()

0.14

In [5]:
result.dG_dict_mat

[None,
 None,
 None,
 None,
 None,
 [{'dG_Helix': 1.0549999999999997,
   'dG_Int': 2.76,
   'dG_Hbond': -0.0,
   'dG_SD': 0.0,
   'dG_nonH': 0.48000000000000004,
   'dG_dipole': 0.0,
   'dG_N_dipole': 0.0,
   'dG_C_dipole': 0.0,
   'dG_i1_tot': 0.0,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.4,
   'dG_Ccap': 0.08}]]

In [6]:
model = AGADIR(method='1s')
result = model.predict('TYQEKAAREVAMKKG')

In [6]:
result.get_helical_propensity()

array([0.        , 0.61472475, 0.64670187, 0.72418318, 0.74460478,
       0.74775882, 0.74832584, 0.73848751, 0.73307215, 0.7129725 ,
       0.6833715 , 0.64183218, 0.58918298, 0.49901381, 0.10019442,
       0.        ])

In [11]:
result.dG_dict_mat

[None,
 None,
 None,
 None,
 None,
 [{'dG_Helix': 3.18,
   'dG_Int': 3.7199999999999998,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': -0.8,
   'dG_dipole': 0.31,
   'dG_N_dipole': 0.36,
   'dG_C_dipole': -0.04999999999999999,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': -0.8,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.8699999999999997,
   'dG_Int': 3.2499999999999996,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': 0.27,
   'dG_N_dipole': 0.25,
   'dG_C_dipole': 0.020000000000000018,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.4,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.26,
   'dG_Int': 2.9299999999999997,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': -0.020000000000000018,
   'dG_N_dipole': 0.12,
   'dG_C_dipole': -0.14,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.5,
   'dG_Ccap': -0.1},
  {'dG_Helix': 3.05,
   'dG_Int': 2.65,
   

In [8]:
result.K_tot_array

array([0.        , 0.09806659, 0.16603706, 0.16603706, 0.16603706,
       0.12516675, 0.        ])

In [5]:
result.Z_array

array([1.        , 1.03169215, 1.03169215, 1.03169215, 1.03169215,
       1.        ])

In [9]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAA')

In [10]:
result.get_percent_helix()

0.234

In [11]:
result.get_helical_propensity()

array([0.        , 0.11644912, 0.17631828, 0.29103264, 0.316181  ,
       0.32869889, 0.33932185, 0.33766947, 0.34087793, 0.32934614,
       0.3085242 , 0.27596996, 0.22545317, 0.1286643 , 0.        ])

In [5]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAA')

In [6]:
result.get_percent_helix()

0.694

In [7]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAAAAKAA')

In [8]:
result.get_percent_helix()

0.83

In [9]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAA')

In [10]:
result.get_percent_helix()

0.924

In [11]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAA')

In [12]:
result.get_percent_helix()

0.94

## Capping

In [12]:
model = AGADIR(method='1s')
result = model.predict('AAQAAAAQAA')
result.get_percent_helix()

case 3


0.033

In [6]:
np.mean(model.result.get_helical_propensity()[1:-1])

0.43973768430365523

In [5]:
result.get_helical_propensity()

array([0.        , 0.24831878, 0.46068257, 0.64587326, 0.75109069,
       0.75109069, 0.64587326, 0.4370944 , 0.23477017, 0.        ])

In [13]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAA')
result.get_percent_helix()

0.025

In [14]:
model = AGADIR(method='1s')
result = model.predict('SAAAAAAA')
result.get_percent_helix()

0.112

In [15]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAG')
result.get_percent_helix()

0.04

In [16]:
model = AGADIR(method='1s')
result = model.predict('SAAAAAAG')
result.get_percent_helix()

0.161

## Side-chain

In [17]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAA')
result.get_percent_helix()

0.025

In [18]:
model = AGADIR(method='1s')
result = model.predict('ADAAAKAA')
result.get_percent_helix()

0.017

In [19]:
model = AGADIR(method='1s')
result = model.predict('ADAAKAAA')
result.get_percent_helix()

0.014

In [20]:
model = AGADIR(method='1s')
result = model.predict('AIAAALAA')
result.get_percent_helix()

0.016

In [21]:
model = AGADIR(method='1s')
result = model.predict('AIAALAAA')
result.get_percent_helix()

0.017

## Coloumb

In [15]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAA')
result.get_percent_helix()

0.386

In [16]:
model = AGADIR(method='1s')
result = model.predict('AAADAAAA')
result.get_percent_helix()

0.257

In [17]:
model = AGADIR(method='1s')
result = model.predict('AAAAKAAA')
result.get_percent_helix()

0.304

In [18]:
model = AGADIR(method='1s')
result = model.predict('AAAKKAAA')
result.get_percent_helix()

0.214

In [19]:
model = AGADIR(method='1s')
result = model.predict('AAADKAAA')
result.get_percent_helix()

0.181

## Dipole

In [20]:
get_dG_dipole('AAAAAAAAAAH')

(0.0, -0.44)

In [21]:
get_dG_dipole('AAAAAAAAAHA')

(0.23, -0.34)

In [22]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.675

In [23]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAAAH')
result.get_percent_helix()

0.688

In [24]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAAHA')
result.get_percent_helix()

0.685

In [25]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAHAA')
result.get_percent_helix()

0.671

In [26]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAHAAA')
result.get_percent_helix()

0.658

In [27]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAHAAAA')
result.get_percent_helix()

0.648

In [28]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAHAAAAA')
result.get_percent_helix()

0.641

In [29]:
model = AGADIR(method='1s')
result = model.predict('AHAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.665

In [30]:
model = AGADIR(method='1s')
result = model.predict('DAAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.691

In [31]:
model = AGADIR(method='1s')
result = model.predict('ADAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.686

In [32]:
model = AGADIR(method='1s')
result = model.predict('AADAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.675

In [33]:
model = AGADIR(method='1s')
result = model.predict('AAADAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.671

In [34]:
model = AGADIR(method='1s')
result = model.predict('AAAADAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.667

In [35]:
model = AGADIR(method='1s')
result = model.predict('AAAAADAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.657