In [12]:
from pyagadir.models import AGADIR
from pyagadir.models import get_dG_dipole, calc_K
import numpy as np

In [7]:
model = AGADIR(method='1s')
result = model.predict('DYQEKSPREVAMKKG')
result.get_percent_helix()

case 1
case 1
case 2


0.026

In [13]:
result.dG_dict_mat

[None,
 None,
 None,
 None,
 None,
 [{'dG_Helix': 3.18,
   'dG_Int': 3.7199999999999998,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': -0.8,
   'dG_dipole': 0.31,
   'dG_N_dipole': 0.36,
   'dG_C_dipole': -0.04999999999999999,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': -0.8,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.8699999999999997,
   'dG_Int': 3.2499999999999996,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': 0.27,
   'dG_N_dipole': 0.25,
   'dG_C_dipole': 0.020000000000000018,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.4,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.26,
   'dG_Int': 2.9299999999999997,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': -0.020000000000000018,
   'dG_N_dipole': 0.12,
   'dG_C_dipole': -0.14,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.5,
   'dG_Ccap': -0.1},
  {'dG_Helix': 3.05,
   'dG_Int': 2.65,
   

In [14]:
model = AGADIR(method='1s')
result = model.predict('TYQEKAAREVAMKKG')
result.get_percent_helix()

case 1
case 1


0.308

In [15]:
result.dG_dict_mat

[None,
 None,
 None,
 None,
 None,
 [{'dG_Helix': 3.18,
   'dG_Int': 3.7199999999999998,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': -0.8,
   'dG_dipole': 0.31,
   'dG_N_dipole': 0.36,
   'dG_C_dipole': -0.04999999999999999,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': -0.8,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.8699999999999997,
   'dG_Int': 3.2499999999999996,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': 0.27,
   'dG_N_dipole': 0.25,
   'dG_C_dipole': 0.020000000000000018,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.4,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.26,
   'dG_Int': 2.9299999999999997,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': -0.020000000000000018,
   'dG_N_dipole': 0.12,
   'dG_C_dipole': -0.14,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.5,
   'dG_Ccap': -0.1},
  {'dG_Helix': 3.05,
   'dG_Int': 2.65,
   

In [6]:
model = AGADIR(method='1s')
result = model.predict('ILKSLEEFLKVTLRSTRQT')

In [7]:
result.get_helical_propensity()

array([0.        , 0.0092098 , 0.01694966, 0.03162682, 0.29314396,
       0.29863254, 0.30385508, 0.3068975 , 0.30417774, 0.29359725,
       0.24265173, 0.19342206, 0.17600071, 0.11319138, 0.03893537,
       0.02254033, 0.01372473, 0.00672205, 0.        ])

In [8]:
result.get_percent_helix()

0.14

In [5]:
result.dG_dict_mat

[None,
 None,
 None,
 None,
 None,
 [{'dG_Helix': 1.0549999999999997,
   'dG_Int': 2.76,
   'dG_Hbond': -0.0,
   'dG_SD': 0.0,
   'dG_nonH': 0.48000000000000004,
   'dG_dipole': 0.0,
   'dG_N_dipole': 0.0,
   'dG_C_dipole': 0.0,
   'dG_i1_tot': 0.0,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.4,
   'dG_Ccap': 0.08}]]

In [6]:
model = AGADIR(method='1s')
result = model.predict('TYQEKAAREVAMKKG')

In [6]:
result.get_helical_propensity()

array([0.        , 0.61472475, 0.64670187, 0.72418318, 0.74460478,
       0.74775882, 0.74832584, 0.73848751, 0.73307215, 0.7129725 ,
       0.6833715 , 0.64183218, 0.58918298, 0.49901381, 0.10019442,
       0.        ])

In [11]:
result.dG_dict_mat

[None,
 None,
 None,
 None,
 None,
 [{'dG_Helix': 3.18,
   'dG_Int': 3.7199999999999998,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': -0.8,
   'dG_dipole': 0.31,
   'dG_N_dipole': 0.36,
   'dG_C_dipole': -0.04999999999999999,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': -0.8,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.8699999999999997,
   'dG_Int': 3.2499999999999996,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': 0.27,
   'dG_N_dipole': 0.25,
   'dG_C_dipole': 0.020000000000000018,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.4,
   'dG_Ccap': 0.0},
  {'dG_Helix': 3.26,
   'dG_Int': 2.9299999999999997,
   'dG_Hbond': -0.0,
   'dG_SD': -0.05,
   'dG_nonH': 0.4,
   'dG_dipole': -0.020000000000000018,
   'dG_N_dipole': 0.12,
   'dG_C_dipole': -0.14,
   'dG_i1_tot': -0.05,
   'dG_i3_tot': 0.0,
   'dG_i4_tot': 0,
   'dG_Ncap': 0.5,
   'dG_Ccap': -0.1},
  {'dG_Helix': 3.05,
   'dG_Int': 2.65,
   

In [8]:
result.K_tot_array

array([0.        , 0.09806659, 0.16603706, 0.16603706, 0.16603706,
       0.12516675, 0.        ])

In [5]:
result.Z_array

array([1.        , 1.03169215, 1.03169215, 1.03169215, 1.03169215,
       1.        ])

In [6]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAA')

0 6 6
1 6 7
2 6 8
3 6 9
4 6 10
5 6 11
6 6 12
7 6 13
8 6 14
9 6 15
0 7 7
1 7 8
2 7 9
3 7 10
4 7 11
5 7 12
6 7 13
7 7 14
8 7 15
0 8 8
1 8 9
2 8 10
3 8 11
4 8 12
5 8 13
6 8 14
7 8 15
0 9 9
1 9 10
2 9 11
3 9 12
4 9 13
5 9 14
6 9 15
0 10 10
1 10 11
2 10 12
3 10 13
4 10 14
5 10 15
0 11 11
1 11 12
2 11 13
3 11 14
4 11 15
0 12 12
1 12 13
2 12 14
3 12 15
0 13 13
1 13 14
2 13 15
0 14 14
1 14 15
0 15 15


In [7]:
result.get_percent_helix()

0.234

In [9]:
result.get_helical_propensity()

array([0.08011586, 0.15317523, 0.25260693, 0.28707561, 0.30423514,
       0.31404149, 0.32231745, 0.33255782, 0.32616148, 0.31796303,
       0.30423514, 0.28452751, 0.25752658, 0.18295556, 0.11185862])

In [5]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAA')

In [6]:
result.get_percent_helix()

0.694

In [7]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAAAAKAA')

In [8]:
result.get_percent_helix()

0.83

In [9]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAA')

In [10]:
result.get_percent_helix()

0.924

In [11]:
model = AGADIR(method='r')
result = model.predict('AAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAA')

In [12]:
result.get_percent_helix()

0.94

## Capping

In [3]:
model = AGADIR(method='1s')
result = model.predict('AAQAAAAQAA')
result.get_percent_helix()

0.417

In [6]:
np.mean(model.result.get_helical_propensity()[1:-1])

0.43973768430365523

In [5]:
result.get_helical_propensity()

array([0.        , 0.24831878, 0.46068257, 0.64587326, 0.75109069,
       0.75109069, 0.64587326, 0.4370944 , 0.23477017, 0.        ])

In [6]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAA')
result.get_percent_helix()

0.386

In [7]:
model = AGADIR(method='1s')
result = model.predict('SAAAAAAA')
result.get_percent_helix()

0.51

In [8]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAG')
result.get_percent_helix()

0.43

In [9]:
model = AGADIR(method='1s')
result = model.predict('SAAAAAAG')
result.get_percent_helix()

0.516

## Side-chain

In [10]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAA')
result.get_percent_helix()

0.386

In [11]:
model = AGADIR(method='1s')
result = model.predict('ADAAAKAA')
result.get_percent_helix()

0.355

In [12]:
model = AGADIR(method='1s')
result = model.predict('ADAAKAAA')
result.get_percent_helix()

0.329

In [13]:
model = AGADIR(method='1s')
result = model.predict('AIAAALAA')
result.get_percent_helix()

0.329

In [14]:
model = AGADIR(method='1s')
result = model.predict('AIAALAAA')
result.get_percent_helix()

0.338

## Coloumb

In [15]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAA')
result.get_percent_helix()

0.386

In [16]:
model = AGADIR(method='1s')
result = model.predict('AAADAAAA')
result.get_percent_helix()

0.257

In [17]:
model = AGADIR(method='1s')
result = model.predict('AAAAKAAA')
result.get_percent_helix()

0.304

In [18]:
model = AGADIR(method='1s')
result = model.predict('AAAKKAAA')
result.get_percent_helix()

0.214

In [19]:
model = AGADIR(method='1s')
result = model.predict('AAADKAAA')
result.get_percent_helix()

0.181

## Dipole

In [20]:
get_dG_dipole('AAAAAAAAAAH')

(0.0, -0.44)

In [21]:
get_dG_dipole('AAAAAAAAAHA')

(0.23, -0.34)

In [22]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.675

In [23]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAAAH')
result.get_percent_helix()

0.688

In [24]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAAHA')
result.get_percent_helix()

0.685

In [25]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAAHAA')
result.get_percent_helix()

0.671

In [26]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAAHAAA')
result.get_percent_helix()

0.658

In [27]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAAHAAAA')
result.get_percent_helix()

0.648

In [28]:
model = AGADIR(method='1s')
result = model.predict('AAAAAAAAAAAAAAAAAAHAAAAA')
result.get_percent_helix()

0.641

In [29]:
model = AGADIR(method='1s')
result = model.predict('AHAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.665

In [30]:
model = AGADIR(method='1s')
result = model.predict('DAAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.691

In [31]:
model = AGADIR(method='1s')
result = model.predict('ADAAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.686

In [32]:
model = AGADIR(method='1s')
result = model.predict('AADAAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.675

In [33]:
model = AGADIR(method='1s')
result = model.predict('AAADAAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.671

In [34]:
model = AGADIR(method='1s')
result = model.predict('AAAADAAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.667

In [35]:
model = AGADIR(method='1s')
result = model.predict('AAAAADAAAAAAAAAAAAAAAAAA')
result.get_percent_helix()

0.657